language: python
python: 3.5

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.3
      env: TOX_ENV=py33
    - python: 3.4
      env: TOX_ENV=py34
    - python: pypy
      env: TOX_ENV=pypy
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.5
      env: TOX_ENV=flake8
    - python: 3.5
      env: TOX_ENV=pylint-errors
    - python: 3.5
      env: TOX_ENV=pylint-full
    - python: 3.5
      env: TOX_ENV=verify-manifest

install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_script:
  - if [ "$TOX_ENV" = "py35" ]; then tox -e coveralls; fi
notifications:
  email: false
